### ISSUE TITLE
I am getting the following error when I give the command gettc 14072

### ISSUE THREAD

**Issue by gaddevarunteja** [seri/gettc#21]
C:\Users\Varun>gettc 14072
C:/Ruby200/lib/ruby/2.0.0/net/http.rb:917:in `connect': SSL_connect returned=1 e
rrno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL
::SSL::SSLError)
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:917:in `block in connect'
        from C:/Ruby200/lib/ruby/2.0.0/timeout.rb:51:in `timeout'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:917:in `connect'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:861:in `do_start'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:850:in `start'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:582:in `start'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/gettc-2.0/lib/gettc/download.rb
:159:in `connect'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/gettc-2.0/lib/gettc/download.rb
:176:in `post_json'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/gettc-2.0/lib/gettc/download.rb
:198:in `get_cookie'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/gettc-2.0/lib/gettc/download.rb
:89:in `initialize'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/gettc-2.0/bin/gettc:36:in `new'

        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/gettc-2.0/bin/gettc:36:in `init
'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/gettc-2.0/bin/gettc:81:in `<top
 (required)>'
        from C:/Ruby200/bin/gettc:23:in `load'
        from C:/Ruby200/bin/gettc:23:in `<main>'

**Comment by seri** [comment]
@gaddevarunteja That has not occurred to me but this may help http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat

Please ping back if it does or doesn't work for you.

**Comment by gaddevarunteja** [comment]
gettc command also not working after updating version.should I delete previous version.

**Comment by seri** [comment]
@gaddevarunteja Usually, you don't have to. But you can certainly try: `gem uninstall gettc && gem install gettc`. Prefix with `sudo` if necessary.

**Comment by gaddevarunteja** [comment]
I have tried setting the path as suggested by the website but still it is showing the same error
