### ISSUE TITLE
undefined local variable

### ISSUE THREAD

**Issue by CookiesBestDinner** [seri/gettc#26]
```text
../../bin/runner.rb:170:in `block in print_failures': undefined local variable or method `j' for #<GettcRu
nner:0x00000000ac1ac0> (NameError)
        from ../../bin/runner.rb:167:in `times'
        from ../../bin/runner.rb:167:in `print_failures'
        from ../../bin/runner.rb:177:in `run'
        from ../../bin/runner.rb:182:in `<main>'
```

I changed `print_case j` to `print_case case_id` which seemed to fix it

I don't know who that code belongs to, but the bug does appear in this repository when grepping for `print_case j`

**Comment by CookiesBestDinner** [comment]
This was fixed in 718e17c45ef52cfef11d78009448e70f6c19c81a
The reason I still ran in to it was likely because my config directory was created before that
