### ISSUE TITLE
'initialize': wrong number of arguments

### ISSUE THREAD

**Issue by livingstonese** [seri/gettc#28]
**Environment**
Mac OS X 10.11.4
ruby installed using brew

When I run gettc, I'm getting the following error. I'm getting the same error for all gettc commands that I try to run like `gettc reset`

```
[~/tet] % gem -v
2.6.8
[~/tet] % ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
[~/tet] % gem install gettc  
Fetching: gettc-2.0.gem (100%)
Successfully installed gettc-2.0
Parsing documentation for gettc-2.0
Installing ri documentation for gettc-2.0
Done installing documentation for gettc after 0 seconds
1 gem installed
[~/tet] % gettc 11127      
/usr/local/lib/ruby/gems/2.4.0/gems/gettc-2.0/lib/gettc/download.rb:206:in `initialize': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/gettc-2.0/lib/gettc/download.rb:206:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/gettc-2.0/lib/gettc/download.rb:206:in `get_cookie'
	from /usr/local/lib/ruby/gems/2.4.0/gems/gettc-2.0/lib/gettc/download.rb:89:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/gettc-2.0/bin/gettc:36:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/gettc-2.0/bin/gettc:36:in `init'
	from /usr/local/lib/ruby/gems/2.4.0/gems/gettc-2.0/bin/gettc:81:in `<top (required)>'
	from /usr/local/bin/gettc:22:in `load'
	from /usr/local/bin/gettc:22:in `<main>'
[~/tet] %
```

**Comment by livingstonese** [comment]
I tried installing ruby 1.9.3 using brew
`brew install ruby193`
After that the gettc command started working
