### ISSUE TITLE
I reinstalled gettc, and now it throwing error

### ISSUE THREAD

**Issue by mukeshtiwari** [seri/gettc#33]
```
➜  SRM 756 git:(master) ✗ gettc 11127
Traceback (most recent call last):
	6: from /usr/local/bin/gettc:23:in `<main>'
	5: from /usr/local/bin/gettc:23:in `load'
	4: from /Library/Ruby/Gems/2.6.0/gems/gettc-2.1/bin/gettc:81:in `<top (required)>'
	3: from /Library/Ruby/Gems/2.6.0/gems/gettc-2.1/bin/gettc:36:in `init'
	2: from /Library/Ruby/Gems/2.6.0/gems/gettc-2.1/bin/gettc:36:in `new'
	1: from /Library/Ruby/Gems/2.6.0/gems/gettc-2.1/lib/gettc/download.rb:85:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/gettc-2.1/lib/gettc/download.rb:156:in `get_cookie': Failed to acquire a JWT token (Gettc::AuthTokenError)
Account: sahiltiwari|
Server Response:
{
  "error": {
    "name": "Internal Server Error",
    "value": 500,
    "description": "Something is broken. Please contact support.",
    "details": "the connection was disabled"
  },
  "serverInformation": {
    "serverName": "TopCoder API",
    "apiVersion": "0.0.1",
    "requestDuration": 487,
    "currentTime": 1581934478618
  },
  "requesterInformation": {
    "id": "some hex code information here",
    "remoteIP" my ip address ",
    "receivedParams": {
      "username": "sahiltiwair",
      "password": "I do not want any one to know password :)",
      "apiVersion": "v2",
      "action": "generateJwt"
    }
  }
}

```

**Comment by vadim0x60** [comment]
I am having the same problem.
But I got the same error when I tried to use Topcoder API directly, bypassing `gettc` entirely

```
vadim0x60@pop-os:~$ http --verbose POST https://api.topcoder.com/v2/auth username=vadim0x60 password=REDACTED
POST /v2/auth HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 54
Content-Type: application/json
Host: api.topcoder.com
User-Agent: HTTPie/0.9.8

{
    "password": "REDACTED",
    "username": "vadim0x60"
}

HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since
Connection: keep-alive
Content-Length: 629
Content-Type: application/json; charset=utf-8
Date: Wed, 19 Feb 2020 19:33:40 GMT
Server: nginx
Set-Cookie: sessionID=2c95aa6e146df67a58e2a59c8dd4b4bf3ebfcbfc;path=/;
X-Powered-By: TopCoder API

{
    "error": {
        "description": "Something is broken. Please contact support.",
        "details": "the connection was disabled",
        "name": "Internal Server Error",
        "value": 500
    },
    "requesterInformation": {
        "id": "2c95aa6e146df67a58e2a59c8dd4b4bf3ebfcbfc-8oGJHQG4MilkdGoe",
        "receivedParams": {
            "action": "generateJwt",
            "apiVersion": "v2",
            "password": "REDACTED",
            "username": "vadim0x60"
        },
        "remoteIP": "31.223.170.141"
    },
    "serverInformation": {
        "apiVersion": "0.0.1",
        "currentTime": 1582140820671,
        "requestDuration": 488,
        "serverName": "TopCoder API"
    }
}

```
So it seems like Topcoder API is broken at the moment

**Comment by jlstr** [comment]
Hello there, did you find the solution for this issue? I'm experiencing the same.
Thanks.
